## Overview:
If you want to learn how to use the [Pywr-DRB](https://github.com/Pywr-DRB/Pywr-DRB) water resource model, you are in the right place. 

This page is designed to introduce you to the Pywr-DRB code base, help you set up your environment, and show you how to access and begin interacting with a Pywr-DRB model instance.  

### Links:
- [The Pywr-DRB GitHub repository](https://github.com/Pywr-DRB/Pywr-DRB)
- [The Pywr-DRB documentation site](https://pywr-drb.github.io/Pywr-DRB/intro.html)

### Tutorial content:
Fill once done.

***
## 1.0 Getting Started

### 2.1 Input Data

Pywr-DRB is able to run simulations using any set of natural streamflow data. It is currently set up to run simulations using multiple different datasets. See the [list of available streamflow scenarios currently implemented in the documentation.](https://pywr-drb.github.io/Pywr-DRB/Model/pywr_drb_inflow_scenarios.html)

Each dataset is given a unique identifying name (e.g., `"nhmv10"`) which is used at multiple points in the Pywr-DRB workflow.

In [1]:
import sys

path_to_pywrdrb = '../'
sys.path.append(path_to_pywrdrb)

> ACTIVITY:

In [2]:
from pywr.model import Model 
from pywrdrb.parameters import *
from pywrdrb.make_model import make_model

# Options: "nhmv10", "nwmv21", "nhmv10_withObsScaled", "nwmv21_withObsScaled" 
inflow_type = 'nwmv21'   

model_filename = f'drb_model_full_{inflow_type}.json'
model_filepath = f'{path_to_pywrdrb}/pywrdrb/model_data/{model_filename}'

if inflow_type in ('nwmv21', 'nhmv10', 'WEAP_29June2023_gridmet') or 'withObsScaled' in inflow_type:
    start_date = '1983-10-01'
    end_date = '2016-12-31'

make_model(inflow_type=inflow_type,
           model_filename=model_filepath,
           start_date=start_date,
           end_date=end_date)

### load the pywrdrb model
model = Model.load(model_filepath)

In [3]:
# Make a list of all model nodes
model_nodes = [n for n in model.nodes if n.name]

print(f'There are {len(model_nodes)} nodes in the model.')

There are 177 nodes in the model.

In [4]:
node_names = [n.name for n in model.nodes]
node_names

['reservoir_cannonsville',
 'catchment_cannonsville',
 'catchmentWithdrawal_cannonsville',
 'catchmentConsumption_cannonsville',
 'outflow_cannonsville',
 'spill_cannonsville',
 'reservoir_pepacton',
 'catchment_pepacton',
 'catchmentWithdrawal_pepacton',
 'catchmentConsumption_pepacton',
 'outflow_pepacton',
 'spill_pepacton',
 'reservoir_neversink',
 'catchment_neversink',
 'catchmentWithdrawal_neversink',
 'catchmentConsumption_neversink',
 'outflow_neversink',
 'spill_neversink',
 'reservoir_wallenpaupack',
 'catchment_wallenpaupack',
 'catchmentWithdrawal_wallenpaupack',
 'catchmentConsumption_wallenpaupack',
 'outflow_wallenpaupack',
 'spill_wallenpaupack',
 'delay_wallenpaupack',
 'reservoir_prompton',
 'catchment_prompton',
 'catchmentWithdrawal_prompton',
 'catchmentConsumption_prompton',
 'outflow_prompton',
 'spill_prompton',
 'delay_prompton',
 'reservoir_shoholaMarsh',
 'catchment_shoholaMarsh',
 'catchmentWithdrawal_shoholaMarsh',
 'catchmentConsumption_shoholaMarsh',
 'outflow_shoholaMarsh',
 'spill_shoholaMarsh',
 'delay_shoholaMarsh',
 'reservoir_mongaupeCombined',
 'catchment_mongaupeCombined',
 'catchmentWithdrawal_mongaupeCombined',
 'catchmentConsumption_mongaupeCombined',
 'outflow_mongaupeCombined',
 'spill_mongaupeCombined',
 'reservoir_beltzvilleCombined',
 'catchment_beltzvilleCombined',
 'catchmentWithdrawal_beltzvilleCombined',
 'catchmentConsumption_beltzvilleCombined',
 'outflow_beltzvilleCombined',
 'spill_beltzvilleCombined',
 'reservoir_fewalter',
 'catchment_fewalter',
 'catchmentWithdrawal_fewalter',
 'catchmentConsumption_fewalter',
 'outflow_fewalter',
 'spill_fewalter',
 'reservoir_merrillCreek',
 'catchment_merrillCreek',
 'catchmentWithdrawal_merrillCreek',
 'catchmentConsumption_merrillCreek',
 'outflow_merrillCreek',
 'spill_merrillCreek',
 'delay_merrillCreek',
 'reservoir_hopatcong',
 'catchment_hopatcong',
 'catchmentWithdrawal_hopatcong',
 'catchmentConsumption_hopatcong',
 'outflow_hopatcong',
 'spill_hopatcong',
 'delay_hopatcong',
 'reservoir_nockamixon',
 'catchment_nockamixon',
 'catchmentWithdrawal_nockamixon',
 'catchmentConsumption_nockamixon',
 'outflow_nockamixon',
 'spill_nockamixon',
 'delay_nockamixon',
 'reservoir_assunpink',
 'catchment_assunpink',
 'catchmentWithdrawal_assunpink',
 'catchmentConsumption_assunpink',
 'outflow_assunpink',
 'spill_assunpink',
 'reservoir_ontelaunee',
 'catchment_ontelaunee',
 'catchmentWithdrawal_ontelaunee',
 'catchmentConsumption_ontelaunee',
 'outflow_ontelaunee',
 'spill_ontelaunee',
 'delay_ontelaunee',
 'reservoir_stillCreek',
 'catchment_stillCreek',
 'catchmentWithdrawal_stillCreek',
 'catchmentConsumption_stillCreek',
 'outflow_stillCreek',
 'spill_stillCreek',
 'delay_stillCreek',
 'reservoir_blueMarsh',
 'catchment_blueMarsh',
 'catchmentWithdrawal_blueMarsh',
 'catchmentConsumption_blueMarsh',
 'outflow_blueMarsh',
 'spill_blueMarsh',
 'reservoir_greenLane',
 'catchment_greenLane',
 'catchmentWithdrawal_greenLane',
 'catchmentConsumption_greenLane',
 'outflow_greenLane',
 'spill_greenLane',
 'delay_greenLane',
 'link_01425000',
 'catchment_01425000',
 'catchmentWithdrawal_01425000',
 'catchmentConsumption_01425000',
 'link_01417000',
 'catchment_01417000',
 'catchmentWithdrawal_01417000',
 'catchmentConsumption_01417000',
 'link_delLordville',
 'catchment_delLordville',
 'catchmentWithdrawal_delLordville',
 'catchmentConsumption_delLordville',
 'delay_delLordville',
 'link_01436000',
 'catchment_01436000',
 'catchmentWithdrawal_01436000',
 'catchmentConsumption_01436000',
 'delay_01436000',
 'link_01433500',
 'catchment_01433500',
 'catchmentWithdrawal_01433500',
 'catchmentConsumption_01433500',
 'link_delMontague',
 'catchment_delMontague',
 'catchmentWithdrawal_delMontague',
 'catchmentConsumption_delMontague',
 'delay_delMontague',
 'link_01449800',
 'catchment_01449800',
 'catchmentWithdrawal_01449800',
 'catchmentConsumption_01449800',
 'delay_01449800',
 'link_01447800',
 'catchment_01447800',
 'catchmentWithdrawal_01447800',
 'catchmentConsumption_01447800',
 'delay_01447800',
 'link_delDRCanal',
 'catchment_delDRCanal',
 'catchmentWithdrawal_delDRCanal',
 'catchmentConsumption_delDRCanal',
 'link_delTrenton',
 'link_01463620',
 'catchment_01463620',
 'catchmentWithdrawal_01463620',
 'catchmentConsumption_01463620',
 'link_outletAssunpink',
 'catchment_outletAssunpink',
 'catchmentWithdrawal_outletAssunpink',
 'catchmentConsumption_outletAssunpink',
 'link_01470960',
 'catchment_01470960',
 'catchmentWithdrawal_01470960',
 'catchmentConsumption_01470960',
 'delay_01470960',
 'link_outletSchuylkill',
 'catchment_outletSchuylkill',
 'catchmentWithdrawal_outletSchuylkill',
 'catchmentConsumption_outletSchuylkill',
 'reservoir_agg_nyc',
 'link_cannonsville_nyc',
 'link_pepacton_nyc',
 'link_neversink_nyc',
 'delivery_nyc',
 'delivery_nj',
 'output_del']

In [5]:
### Read model parameter names into a list
model_parameters = [p for p in model.parameters if p.name]

print(f'There are {len(model_parameters)} parameters in the model')

There are 394 parameters in the model

## 4.0 Running a PywrDRB simulation

In [6]:
# The pywr.recorders.TablesRecorder class is used store simulation results
# the simulation data is stored in an hdf5 file which is accessed during the simulation
from pywr.recorders import TablesRecorder

output_filename = f'drb_output_{inflow_type}.hdf5'
output_filepath = f'../output_data/{output_filename}'

### Add a storage recorder
TablesRecorder(model = model, 
			   h5file = output_filepath, 
			   parameters = model_parameters)

### Run the model
stats = model.run()

c:\Users\ms3654\Desktop\Research\Delaware\Pywr-DRB\Pywr-DRB\venv\Lib\site-packages\pywr\dataframe_tools.py:127: FutureWarning: Resampling with a PeriodIndex is deprecated. Cast index to DatetimeIndex before resampling instead.
  new_df = new_df.resample(target_index.freq).agg(resample_func)
c:\Users\ms3654\Desktop\Research\Delaware\Pywr-DRB\Pywr-DRB\venv\Lib\site-packages\tables\attributeset.py:457: NaturalNameWarning: object name is not a valid Python identifier: 'pywr-attribute'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  check_attribute_name(name)
c:\Users\ms3654\Desktop\Research\Delaware\Pywr-DRB\Pywr-DRB\venv\Lib\site-packages\tables\attributeset.py:457: NaturalNameWarning: object name is not a valid Python identifier: 'pywr-type'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  check_attribute_name(name)
c:\Users\ms3654\Desktop\Research\Delaware\Pywr-DRB\Pywr-DRB\venv\Lib\site-packages\tables\path.py:137: NaturalNameWarning: object name is not a valid Python identifier: 'delay_wallenpaupack - delay parameter'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  check_attribute_name(name)
c:\Users\ms3654\Desktop\Research\Delaware\Pywr-DRB\Pywr-DRB\venv\Lib\site-packages\tables\path.py:137: NaturalNameWarning: object name is not a valid Python identifier: 'delay_prompton - delay parameter'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  check_attribute_name(name)
c:\Users\ms3654\Desktop\Research\Delaware\Pywr-DRB\Pywr-DRB\venv\Lib\site-packages\tables\path.py:137: NaturalNameWarning: object name is not a valid Python identifier: 'delay_shoholaMarsh - delay parameter'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  check_attribute_name(name)
c:\Users\ms3654\Desktop\Research\Delaware\Pywr-DRB\Pywr-DRB\venv\Lib\site-packages\tables\path.py:137: NaturalNameWarning: object name is not a valid Python identifier: 'delay_merrillCreek - delay parameter'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  check_attribute_name(name)
c:\Users\ms3654\Desktop\Research\Delaware\Pywr-DRB\Pywr-DRB\venv\Lib\site-packages\tables\path.py:137: NaturalNameWarning: object name is not a valid Python identifier: 'delay_hopatcong - delay parameter'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  check_attribute_name(name)
c:\Users\ms3654\Desktop\Research\Delaware\Pywr-DRB\Pywr-DRB\venv\Lib\site-packages\tables\path.py:137: NaturalNameWarning: object name is not a valid Python identifier: 'delay_nockamixon - delay parameter'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  check_attribute_name(name)
c:\Users\ms3654\Desktop\Research\Delaware\Pywr-DRB\Pywr-DRB\venv\Lib\site-packages\tables\path.py:137: NaturalNameWarning: object name is not a valid Python identifier: 'delay_ontelaunee - delay parameter'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  check_attribute_name(name)
c:\Users\ms3654\Desktop\Research\Delaware\Pywr-DRB\Pywr-DRB\venv\Lib\site-packages\tables\path.py:137: NaturalNameWarning: object name is not a valid Python identifier: 'delay_stillCreek - delay parameter'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  check_attribute_name(name)
c:\Users\ms3654\Desktop\Research\Delaware\Pywr-DRB\Pywr-DRB\venv\Lib\site-packages\tables\path.py:137: NaturalNameWarning: object name is not a valid Python identifier: 'delay_greenLane - delay parameter'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  check_attribute_name(name)
c:\Users\ms3654\Desktop\Research\Delaware\Pywr-DRB\Pywr-DRB\venv\Lib\site-packages\tables\path.py:137: NaturalNameWarning: object name is not a valid Python identifier: 'delay_delLordville - delay parameter'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  check_attribute_name(name)
c:\Users\ms3654\Desktop\Research\Delaware\Pywr-DRB\Pywr-DRB\venv\Lib\site-packages\tables\path.py:137: NaturalNameWarning: object name is not a valid Python identifier: 'delay_01436000 - delay parameter'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  check_attribute_name(name)
c:\Users\ms3654\Desktop\Research\Delaware\Pywr-DRB\Pywr-DRB\venv\Lib\site-packages\tables\path.py:137: NaturalNameWarning: object name is not a valid Python identifier: 'delay_delMontague - delay parameter'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  check_attribute_name(name)
c:\Users\ms3654\Desktop\Research\Delaware\Pywr-DRB\Pywr-DRB\venv\Lib\site-packages\tables\path.py:137: NaturalNameWarning: object name is not a valid Python identifier: 'delay_01449800 - delay parameter'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  check_attribute_name(name)
c:\Users\ms3654\Desktop\Research\Delaware\Pywr-DRB\Pywr-DRB\venv\Lib\site-packages\tables\path.py:137: NaturalNameWarning: object name is not a valid Python identifier: 'delay_01447800 - delay parameter'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  check_attribute_name(name)
c:\Users\ms3654\Desktop\Research\Delaware\Pywr-DRB\Pywr-DRB\venv\Lib\site-packages\tables\path.py:137: NaturalNameWarning: object name is not a valid Python identifier: 'delay_01470960 - delay parameter'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  check_attribute_name(name)
C:\Users\ms3654\AppData\Local\Temp\ipykernel_47056\3705744310.py:14: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  stats = model.run()

S<ScenarioIndex gid=0 indices=(0,)>: <Timestep date="1991-11-07"> Lower Basin MRF releases: {'beltzvilleCombined': 6.644145649857073, 'blueMarsh': 0.0, 'nockamixon': 0.0}
S<ScenarioIndex gid=0 indices=(0,)>: <Timestep date="1991-11-07"> Lower Basin MRF releases: {'beltzvilleCombined': 6.644145649857073, 'blueMarsh': 0.0, 'nockamixon': 0.0}
S<ScenarioIndex gid=0 indices=(0,)>: <Timestep date="1991-11-08"> Lower Basin MRF releases: {'beltzvilleCombined': 40.84030534267558, 'blueMarsh': 0.0, 'nockamixon': 0.0}
S<ScenarioIndex gid=0 indices=(0,)>: <Timestep date="1991-11-08"> Lower Basin MRF releases: {'beltzvilleCombined': 40.84030534267558, 'blueMarsh': 0.0, 'nockamixon': 0.0}
S<ScenarioIndex gid=0 indices=(0,)>: <Timestep date="1991-11-09"> Lower Basin MRF releases: {'beltzvilleCombined': 61.85872366176933, 'blueMarsh': 0.0, 'nockamixon': 0.0}
S<ScenarioIndex gid=0 indices=(0,)>: <Timestep date="1991-11-09"> Lower Basin MRF releases: {'beltzvilleCombined': 61.85872366176933, 'blueMarsh': 0.0, 'nockamixon': 0.0}
S<ScenarioIndex gid=0 indices=(0,)>: <Timestep date="1991-11-10"> Lower Basin MRF releases: {'beltzvilleCombined': 80.23337035985706, 'blueMarsh': 0.0, 'nockamixon': 0.0}
S<ScenarioIndex gid=0 indices=(0,)>: <Timestep date="1991-11-10"> Lower Basin MRF releases: {'beltzvilleCombined': 80.23337035985706, 'blueMarsh': 0.0, 'nockamixon': 0.0}
S<ScenarioIndex gid=0 indices=(0,)>: <Timestep date="1991-11-11"> Lower Basin MRF releases: {'beltzvilleCombined': 102.11942834852118, 'blueMarsh': 0.0, 'nockamixon': 0.0}
S<ScenarioIndex gid=0 indices=(0,)>: <Timestep date="1991-11-11"> Lower Basin MRF releases: {'beltzvilleCombined': 102.11942834852118, 'blueMarsh': 0.0, 'nockamixon': 0.0}
S<ScenarioIndex gid=0 indices=(0,)>: <Timestep date="1991-11-12"> Lower Basin MRF releases: {'beltzvilleCombined': 103.01886538343248, 'blueMarsh': 0.0, 'nockamixon': 0.0}
S<ScenarioIndex gid=0 indices=(0,)>: <Timestep date="1991-11-12"> Lower Basin MRF releases: {'beltzvilleCombined': 103.01886538343248, 'blueMarsh': 0.0, 'nockamixon': 0.0}
S<ScenarioIndex gid=0 indices=(0,)>: <Timestep date="1991-11-13"> Lower Basin MRF releases: {'beltzvilleCombined': 90.20347721407418, 'blueMarsh': 0.0, 'nockamixon': 0.0}
S<ScenarioIndex gid=0 indices=(0,)>: <Timestep date="1991-11-13"> Lower Basin MRF releases: {'beltzvilleCombined': 90.20347721407418, 'blueMarsh': 0.0, 'nockamixon': 0.0}
S<ScenarioIndex gid=0 indices=(0,)>: <Timestep date="1991-11-14"> Lower Basin MRF releases: {'beltzvilleCombined': 90.73222010473165, 'blueMarsh': 0.0, 'nockamixon': 0.0}
S<ScenarioIndex gid=0 indices=(0,)>: <Timestep date="1991-11-14"> Lower Basin MRF releases: {'beltzvilleCombined': 90.73222010473165, 'blueMarsh': 0.0, 'nockamixon': 0.0}
S<ScenarioIndex gid=0 indices=(0,)>: <Timestep date="1991-11-15"> Lower Basin MRF releases: {'beltzvilleCombined': 98.5481830171892, 'blueMarsh': 0.0, 'nockamixon': 0.0}
S<ScenarioIndex gid=0 indices=(0,)>: <Timestep date="1991-11-15"> Lower Basin MRF releases: {'beltzvilleCombined': 98.5481830171892, 'blueMarsh': 0.0, 'nockamixon': 0.0}
S<ScenarioIndex gid=0 indices=(0,)>: <Timestep date="1991-11-16"> Lower Basin MRF releases: {'beltzvilleCombined': 145.08407784029475, 'blueMarsh': 0.0, 'nockamixon': 0.0}
S<ScenarioIndex gid=0 indices=(0,)>: <Timestep date="1991-11-16"> Lower Basin MRF releases: {'beltzvilleCombined': 145.08407784029475, 'blueMarsh': 0.0, 'nockamixon': 0.0}
S<ScenarioIndex gid=0 indices=(0,)>: <Timestep date="1991-11-17"> Lower Basin MRF releases: {'beltzvilleCombined': 95.8978515071561, 'blueMarsh': 0.0, 'nockamixon': 0.0}
S<ScenarioIndex gid=0 indices=(0,)>: <Timestep date="1991-11-17"> Lower Basin MRF releases: {'beltzvilleCombined': 95.8978515071561, 'blueMarsh': 0.0, 'nockamixon': 0.0}
S<ScenarioIndex gid=0 indices=(0,)>: <Timestep date="1991-11-18"> Lower Basin MRF releases: {'beltzvilleCombined': 63.64047483640151, 'blueMarsh': 0.0, 'nockamixon': 0.0}
S<ScenarioIndex gid=0 indices=(0,)>: <Timestep date="1991-11-18"> Lower Basin MRF releases: {'beltzvilleCombined': 63.64047483640151, 'blueMarsh': 0.0, 'nockamixon': 0.0}
S<ScenarioIndex gid=0 indices=(0,)>: <Timestep date="1991-11-19"> Lower Basin MRF releases: {'beltzvilleCombined': 79.17651207044898, 'blueMarsh': 0.0, 'nockamixon': 0.0}
S<ScenarioIndex gid=0 indices=(0,)>: <Timestep date="1991-11-19"> Lower Basin MRF releases: {'beltzvilleCombined': 79.17651207044898, 'blueMarsh': 0.0, 'nockamixon': 0.0}
S<ScenarioIndex gid=0 indices=(0,)>: <Timestep date="1991-11-20"> Lower Basin MRF releases: {'beltzvilleCombined': 72.35310552471059, 'blueMarsh': 0.0, 'nockamixon': 0.0}
S<ScenarioIndex gid=0 indices=(0,)>: <Timestep date="1991-11-20"> Lower Basin MRF releases: {'beltzvilleCombined': 72.35310552471059, 'blueMarsh': 0.0, 'nockamixon': 0.0}
S<ScenarioIndex gid=0 indices=(0,)>: <Timestep date="1991-11-21"> Lower Basin MRF releases: {'beltzvilleCombined': 90.4732453185056, 'blueMarsh': 0.0, 'nockamixon': 0.0}
S<ScenarioIndex gid=0 indices=(0,)>: <Timestep date="1991-11-21"> Lower Basin MRF releases: {'beltzvilleCombined': 90.4732453185056, 'blueMarsh': 0.0, 'nockamixon': 0.0}
S<ScenarioIndex gid=0 indices=(0,)>: <Timestep date="1991-11-22"> Lower Basin MRF releases: {'beltzvilleCombined': 300.0, 'blueMarsh': 0.0, 'nockamixon': 0.0}
S<ScenarioIndex gid=0 indices=(0,)>: <Timestep date="1991-11-22"> Lower Basin MRF releases: {'beltzvilleCombined': 300.0, 'blueMarsh': 0.0, 'nockamixon': 0.0}
S<ScenarioIndex gid=0 indices=(0,)>: <Timestep date="1994-02-21"> Lower Basin MRF releases: {'beltzvilleCombined': 300.0, 'blueMarsh': 11.62726718125657, 'nockamixon': 0.0}
S<ScenarioIndex gid=0 indices=(0,)>: <Timestep date="1994-02-21"> Lower Basin MRF releases: {'beltzvilleCombined': 300.0, 'blueMarsh': 11.62726718125657, 'nockamixon': 0.0}
S<ScenarioIndex gid=0 indices=(0,)>: <Timestep date="1995-09-23"> Lower Basin MRF releases: {'beltzvilleCombined': 25.938588462997075, 'blueMarsh': 0.0, 'nockamixon': 0.0}
S<ScenarioIndex gid=0 indices=(0,)>: <Timestep date="1995-09-23"> Lower Basin MRF releases: {'beltzvilleCombined': 25.938588462997075, 'blueMarsh': 0.0, 'nockamixon': 0.0}
S<ScenarioIndex gid=0 indices=(0,)>: <Timestep date="1995-09-24"> Lower Basin MRF releases: {'beltzvilleCombined': 257.7854094544857, 'blueMarsh': 0.0, 'nockamixon': 0.0}
S<ScenarioIndex gid=0 indices=(0,)>: <Timestep date="1995-09-24"> Lower Basin MRF releases: {'beltzvilleCombined': 257.7854094544857, 'blueMarsh': 0.0, 'nockamixon': 0.0}
S<ScenarioIndex gid=0 indices=(0,)>: <Timestep date="1995-09-25"> Lower Basin MRF releases: {'beltzvilleCombined': 269.33754158123236, 'blueMarsh': 0.0, 'nockamixon': 0.0}
S<ScenarioIndex gid=0 indices=(0,)>: <Timestep date="1995-09-25"> Lower Basin MRF releases: {'beltzvilleCombined': 269.33754158123236, 'blueMarsh': 0.0, 'nockamixon': 0.0}
S<ScenarioIndex gid=0 indices=(0,)>: <Timestep date="1995-09-26"> Lower Basin MRF releases: {'beltzvilleCombined': 235.84507233906493, 'blueMarsh': 0.0, 'nockamixon': 0.0}
S<ScenarioIndex gid=0 indices=(0,)>: <Timestep date="1995-09-26"> Lower Basin MRF releases: {'beltzvilleCombined': 235.84507233906493, 'blueMarsh': 0.0, 'nockamixon': 0.0}
S<ScenarioIndex gid=0 indices=(0,)>: <Timestep date="1995-09-27"> Lower Basin MRF releases: {'beltzvilleCombined': 193.65457423263794, 'blueMarsh': 0.0, 'nockamixon': 0.0}
S<ScenarioIndex gid=0 indices=(0,)>: <Timestep date="1995-09-27"> Lower Basin MRF releases: {'beltzvilleCombined': 193.65457423263794, 'blueMarsh': 0.0, 'nockamixon': 0.0}
S<ScenarioIndex gid=0 indices=(0,)>: <Timestep date="1995-09-28"> Lower Basin MRF releases: {'beltzvilleCombined': 254.73696319582388, 'blueMarsh': 0.0, 'nockamixon': 0.0}
S<ScenarioIndex gid=0 indices=(0,)>: <Timestep date="1995-09-28"> Lower Basin MRF releases: {'beltzvilleCombined': 254.73696319582388, 'blueMarsh': 0.0, 'nockamixon': 0.0}
S<ScenarioIndex gid=0 indices=(0,)>: <Timestep date="1995-09-29"> Lower Basin MRF releases: {'beltzvilleCombined': 251.90749614079243, 'blueMarsh': 0.0, 'nockamixon': 0.0}
S<ScenarioIndex gid=0 indices=(0,)>: <Timestep date="1995-09-29"> Lower Basin MRF releases: {'beltzvilleCombined': 251.90749614079243, 'blueMarsh': 0.0, 'nockamixon': 0.0}
S<ScenarioIndex gid=0 indices=(0,)>: <Timestep date="1995-09-30"> Lower Basin MRF releases: {'beltzvilleCombined': 258.51015430594384, 'blueMarsh': 0.0, 'nockamixon': 0.0}
S<ScenarioIndex gid=0 indices=(0,)>: <Timestep date="1995-09-30"> Lower Basin MRF releases: {'beltzvilleCombined': 258.51015430594384, 'blueMarsh': 0.0, 'nockamixon': 0.0}
S<ScenarioIndex gid=0 indices=(0,)>: <Timestep date="1995-10-01"> Lower Basin MRF releases: {'beltzvilleCombined': 267.5896502335953, 'blueMarsh': 0.0, 'nockamixon': 0.0}
S<ScenarioIndex gid=0 indices=(0,)>: <Timestep date="1995-10-01"> Lower Basin MRF releases: {'beltzvilleCombined': 267.5896502335953, 'blueMarsh': 0.0, 'nockamixon': 0.0}
S<ScenarioIndex gid=0 indices=(0,)>: <Timestep date="1995-10-02"> Lower Basin MRF releases: {'beltzvilleCombined': 248.40960262971532, 'blueMarsh': 0.0, 'nockamixon': 0.0}
S<ScenarioIndex gid=0 indices=(0,)>: <Timestep date="1995-10-02"> Lower Basin MRF releases: {'beltzvilleCombined': 248.40960262971532, 'blueMarsh': 0.0, 'nockamixon': 0.0}
S<ScenarioIndex gid=0 indices=(0,)>: <Timestep date="1995-10-03"> Lower Basin MRF releases: {'beltzvilleCombined': 203.75157907013897, 'blueMarsh': 0.0, 'nockamixon': 0.0}
S<ScenarioIndex gid=0 indices=(0,)>: <Timestep date="1995-10-03"> Lower Basin MRF releases: {'beltzvilleCombined': 203.75157907013897, 'blueMarsh': 0.0, 'nockamixon': 0.0}
S<ScenarioIndex gid=0 indices=(0,)>: <Timestep date="1995-10-04"> Lower Basin MRF releases: {'beltzvilleCombined': 271.82580725341563, 'blueMarsh': 0.0, 'nockamixon': 0.0}
S<ScenarioIndex gid=0 indices=(0,)>: <Timestep date="1995-10-04"> Lower Basin MRF releases: {'beltzvilleCombined': 271.82580725341563, 'blueMarsh': 0.0, 'nockamixon': 0.0}
S<ScenarioIndex gid=0 indices=(0,)>: <Timestep date="1995-10-05"> Lower Basin MRF releases: {'beltzvilleCombined': 245.91289666515672, 'blueMarsh': 0.0, 'nockamixon': 0.0}
S<ScenarioIndex gid=0 indices=(0,)>: <Timestep date="1995-10-05"> Lower Basin MRF releases: {'beltzvilleCombined': 245.91289666515672, 'blueMarsh': 0.0, 'nockamixon': 0.0}
S<ScenarioIndex gid=0 indices=(0,)>: <Timestep date="1995-10-06"> Lower Basin MRF releases: {'beltzvilleCombined': 163.45799730825343, 'blueMarsh': 0.0, 'nockamixon': 0.0}
S<ScenarioIndex gid=0 indices=(0,)>: <Timestep date="1995-10-06"> Lower Basin MRF releases: {'beltzvilleCombined': 163.45799730825343, 'blueMarsh': 0.0, 'nockamixon': 0.0}
S<ScenarioIndex gid=0 indices=(0,)>: <Timestep date="1995-10-07"> Lower Basin MRF releases: {'beltzvilleCombined': 94.53077407854936, 'blueMarsh': 0.0, 'nockamixon': 0.0}
S<ScenarioIndex gid=0 indices=(0,)>: <Timestep date="1995-10-07"> Lower Basin MRF releases: {'beltzvilleCombined': 94.53077407854936, 'blueMarsh': 0.0, 'nockamixon': 0.0}
S<ScenarioIndex gid=0 indices=(0,)>: <Timestep date="1995-10-14"> Lower Basin MRF releases: {'beltzvilleCombined': 33.85766837542256, 'blueMarsh': 0.0, 'nockamixon': 0.0}
S<ScenarioIndex gid=0 indices=(0,)>: <Timestep date="1995-10-14"> Lower Basin MRF releases: {'beltzvilleCombined': 33.85766837542256, 'blueMarsh': 0.0, 'nockamixon': 0.0}
S<ScenarioIndex gid=0 indices=(0,)>: <Timestep date="2002-10-10"> Lower Basin MRF releases: {'beltzvilleCombined': 15.80530891097439, 'blueMarsh': 0.0, 'nockamixon': 0.0}
S<ScenarioIndex gid=0 indices=(0,)>: <Timestep date="2002-10-10"> Lower Basin MRF releases: {'beltzvilleCombined': 15.80530891097439, 'blueMarsh': 0.0, 'nockamixon': 0.0}
S<ScenarioIndex gid=0 indices=(0,)>: <Timestep date="2016-11-21"> Lower Basin MRF releases: {'beltzvilleCombined': 92.62224509740469, 'blueMarsh': 0.0, 'nockamixon': 0.0}
S<ScenarioIndex gid=0 indices=(0,)>: <Timestep date="2016-11-21"> Lower Basin MRF releases: {'beltzvilleCombined': 92.62224509740469, 'blueMarsh': 0.0, 'nockamixon': 0.0}
S<ScenarioIndex gid=0 indices=(0,)>: <Timestep date="2016-11-22"> Lower Basin MRF releases: {'beltzvilleCombined': 83.83711555631936, 'blueMarsh': 0.0, 'nockamixon': 0.0}
S<ScenarioIndex gid=0 indices=(0,)>: <Timestep date="2016-11-22"> Lower Basin MRF releases: {'beltzvilleCombined': 83.83711555631936, 'blueMarsh': 0.0, 'nockamixon': 0.0}
S<ScenarioIndex gid=0 indices=(0,)>: <Timestep date="2016-11-23"> Lower Basin MRF releases: {'beltzvilleCombined': 81.4685698100464, 'blueMarsh': 0.0, 'nockamixon': 0.0}
S<ScenarioIndex gid=0 indices=(0,)>: <Timestep date="2016-11-23"> Lower Basin MRF releases: {'beltzvilleCombined': 81.4685698100464, 'blueMarsh': 0.0, 'nockamixon': 0.0}
S<ScenarioIndex gid=0 indices=(0,)>: <Timestep date="2016-11-24"> Lower Basin MRF releases: {'beltzvilleCombined': 92.82499625007614, 'blueMarsh': 0.0, 'nockamixon': 0.0}
S<ScenarioIndex gid=0 indices=(0,)>: <Timestep date="2016-11-24"> Lower Basin MRF releases: {'beltzvilleCombined': 92.82499625007614, 'blueMarsh': 0.0, 'nockamixon': 0.0}
S<ScenarioIndex gid=0 indices=(0,)>: <Timestep date="2016-11-25"> Lower Basin MRF releases: {'beltzvilleCombined': 121.0023888812072, 'blueMarsh': 0.0, 'nockamixon': 0.0}
S<ScenarioIndex gid=0 indices=(0,)>: <Timestep date="2016-11-25"> Lower Basin MRF releases: {'beltzvilleCombined': 121.0023888812072, 'blueMarsh': 0.0, 'nockamixon': 0.0}
S<ScenarioIndex gid=0 indices=(0,)>: <Timestep date="2016-11-26"> Lower Basin MRF releases: {'beltzvilleCombined': 134.3903138864718, 'blueMarsh': 0.0, 'nockamixon': 0.0}
S<ScenarioIndex gid=0 indices=(0,)>: <Timestep date="2016-11-26"> Lower Basin MRF releases: {'beltzvilleCombined': 134.3903138864718, 'blueMarsh': 0.0, 'nockamixon': 0.0}
S<ScenarioIndex gid=0 indices=(0,)>: <Timestep date="2016-11-27"> Lower Basin MRF releases: {'beltzvilleCombined': 115.79166189922441, 'blueMarsh': 0.0, 'nockamixon': 0.0}
S<ScenarioIndex gid=0 indices=(0,)>: <Timestep date="2016-11-27"> Lower Basin MRF releases: {'beltzvilleCombined': 115.79166189922441, 'blueMarsh': 0.0, 'nockamixon': 0.0}
S<ScenarioIndex gid=0 indices=(0,)>: <Timestep date="2016-11-28"> Lower Basin MRF releases: {'beltzvilleCombined': 110.5370566255254, 'blueMarsh': 0.0, 'nockamixon': 0.0}
S<ScenarioIndex gid=0 indices=(0,)>: <Timestep date="2016-11-28"> Lower Basin MRF releases: {'beltzvilleCombined': 110.5370566255254, 'blueMarsh': 0.0, 'nockamixon': 0.0}
S<ScenarioIndex gid=0 indices=(0,)>: <Timestep date="2016-11-29"> Lower Basin MRF releases: {'beltzvilleCombined': 92.57499531227701, 'blueMarsh': 0.0, 'nockamixon': 0.0}
S<ScenarioIndex gid=0 indices=(0,)>: <Timestep date="2016-11-29"> Lower Basin MRF releases: {'beltzvilleCombined': 92.57499531227701, 'blueMarsh': 0.0, 'nockamixon': 0.0}

In [7]:
from pywrdrb.post import get_pywr_results
inflow_type = 'nwmv21'
# Get the simulation results at major flow nodes
major_flows, datetime = get_pywr_results(output_dir= '../output_data/',
                           model = inflow_type, 
                           results_set= 'major_flow')

# Get reservoir release results
res_releases, datetime = get_pywr_results(output_dir= '../output_data/',
                           model = inflow_type, 
                           results_set= 'res_release',
                           datetime_index=datetime)
res_releases.head()

,cannonsville,pepacton,neversink,wallenpaupack,prompton,shoholaMarsh,mongaupeCombined,beltzvilleCombined,fewalter,merrillCreek,hopatcong,nockamixon,assunpink,ontelaunee,stillCreek,blueMarsh,greenLane
1983-10-01,357.135601,494.666815,195.717508,707.928318,231.606514,171.077311,674.432092,22.492552,1291.864737,9.307315,86.425066,645.932369,75.028354,23.74315,23.74315,968.898553,322.52695
1983-10-02,363.028015,501.900880,91.280429,707.928318,231.606514,171.077311,674.432092,22.492552,1291.864737,9.307315,86.425066,645.932369,75.028354,23.74315,23.74315,968.898553,322.52695
1983-10-03,371.412317,513.177544,101.600291,707.928318,231.606514,171.077311,674.432092,22.492552,1291.864737,9.307315,86.425066,645.932369,75.028354,23.74315,23.74315,968.898553,322.52695
1983-10-04,375.878753,518.968648,94.861968,707.928318,231.606514,171.077311,674.432092,22.492552,1291.864737,9.307315,86.425066,645.932369,75.028354,23.74315,23.74315,968.898553,322.52695
1983-10-05,379.322493,523.345086,94.713285,707.928318,231.606514,171.077311,674.432092,22.492552,1291.864737,9.307315,86.425066,645.932369,75.028354,23.74315,23.74315,968.898553,322.52695

In [9]:
major_flows.head()

,01417000,01425000,01433500,01436000,01447800,01449800,01463620,01470960,delDRCanal,delLordville,delMontague,delTrenton,outletAssunpink,outletSchuylkill
1983-10-01,542.664880,377.312284,675.886867,236.717440,1299.034020,31.668093,76.568704,991.195594,664.927243,995.825137,904.334078,572.989312,128.950111,471.527748
1983-10-02,549.404512,382.405998,675.801279,132.061669,1298.720245,31.882343,76.853862,991.262152,1377.978152,1007.163131,2250.381961,1288.667019,137.530275,732.643197
1983-10-03,559.968052,390.134225,675.886855,142.077266,1298.349420,32.091526,78.829758,991.262152,3590.182072,1025.226697,3138.423086,3500.870939,130.067272,1767.217492
1983-10-04,565.065047,394.087211,675.801279,135.101234,1297.997612,32.300710,76.934781,991.110019,4921.817449,1034.381270,3158.112717,4835.133114,124.979398,1758.412775
1983-10-05,568.756885,397.074551,675.877347,134.667301,1297.645804,32.528910,76.670774,990.853294,5802.042585,1041.440782,3167.079894,5715.358249,119.049835,1749.921834

In [11]:
# Get reservoir release results
res_storage, datetime = get_pywr_results(output_dir= '../output_data/',
                           model = inflow_type, 
                           results_set= 'res_storage',
                           datetime_index=datetime)
res_storage.head()

,assunpink,beltzvilleCombined,blueMarsh,cannonsville,fewalter,greenLane,hopatcong,merrillCreek,mongaupeCombined,neversink,nockamixon,ontelaunee,pepacton,prompton,shoholaMarsh,stillCreek,wallenpaupack
1983-10-01,3221.838206,10813.971906,32896.807725,75961.685254,27399.698953,6230.764250,12489.303134,11973.534605,22087.198214,27701.805803,17871.348991,3011.496521,111283.472024,22137.773485,6724.261974,2999.297330,69686.480623
1983-10-02,3146.809852,10825.843369,31935.900821,75496.402137,26158.992979,5910.039401,12403.946412,11964.227290,21476.638253,27532.132532,17229.522554,2999.519744,110601.789540,21910.676432,6558.885151,2976.448839,68997.359105
1983-10-03,3071.781497,10837.505649,30974.993917,74852.299003,24918.049986,5589.181435,12318.570674,11954.919976,20865.878645,27297.240167,16587.696116,2987.381324,109658.181814,21683.417737,6393.508327,2953.600349,68308.075953
1983-10-04,2996.753143,10848.958746,30014.239147,74205.370296,23676.879390,5268.228386,12232.985753,11945.612661,20255.090588,27061.317368,15945.869678,2975.014705,108710.434638,21456.092483,6228.131503,2930.751858,67618.631164
1983-10-05,2921.724789,10860.183643,29053.741101,73547.222100,22435.490673,4947.275337,12147.400832,11936.305346,19644.093357,26821.303031,15304.043240,2962.495953,107746.250970,21228.767229,6062.754680,2907.903368,66928.977198

In [12]:
# Get reservoir release results
inflow, datetime = get_pywr_results(output_dir= '../output_data/',
                           model = inflow_type, 
                           results_set= 'inflow',
                           datetime_index=datetime)
inflow.head()


#https://pywr-drb.github.io/Pywr-DRB/Getting_Started/Interpret_Results/explore_model_outputs.html

,01417000,01425000,01433500,01436000,01447800,01449800,01463620,01470960,assunpink,beltzvilleCombined,...,neversink,nockamixon,ontelaunee,outletAssunpink,outletSchuylkill,pepacton,prompton,shoholaMarsh,stillCreek,wallenpaupack
1983-10-01,47.998066,20.176683,1.454775,40.999932,7.169283,9.175541,1.540350,22.297041,0.0,36.464458,...,18.332066,4.1076,13.111991,52.381407,471.527748,27.155799,4.564000,5.733525,0.9128,18.988141
1983-10-02,47.503632,19.377983,1.369200,40.781241,6.855508,9.394233,1.835108,22.363600,0.0,36.245766,...,18.617316,4.1076,12.940841,61.005465,470.919214,26.927599,4.564000,5.705000,0.9128,18.807483
1983-10-03,46.790507,18.721908,1.454775,40.476974,6.484683,9.603416,3.812842,22.363600,0.0,36.036583,...,18.683875,4.1076,12.779200,51.620741,466.811615,26.927599,4.402358,5.705000,0.9128,18.645841
1983-10-04,46.096399,18.208458,1.369200,40.239266,6.132875,9.812600,1.930192,22.211466,0.0,35.827399,...,18.864533,4.1076,12.551000,48.368891,457.940340,26.927599,4.335800,5.705000,0.9128,18.484200
1983-10-05,45.411799,17.752058,1.445267,39.954016,5.781067,10.040800,1.654450,21.954741,0.0,35.599199,...,19.149783,4.1076,12.398866,42.682907,449.449398,26.927599,4.335800,5.705000,0.9128,18.275016